server:
  port: 8121
spring:
  application:
    name: bestoj-backend-gateway
  cloud:
    nacos:
      server-addr: 192.168.115.131:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bestoj-backend-user-service
          uri: lb://bestoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: bestoj-backend-judge-service
          uri: lb://bestoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
        - id: bestoj-backend-question-service
          uri: lb://bestoj-backend-question-service
          predicates:
            - Path=/api/question/**, /api/questionsubmit/**
  main:
    web-application-type: reactive
# 接口文档配置
knife4j:
  gateway:
    enabled: true
    # 排序规则(tag/operation排序自4.2.0版本新增)
    # 取值：alpha-默认排序规则，官方swagger-ui默认实现,order-Knife4j提供的增强排序规则，开发者可扩展x-order，根据数值来自定义排序
    tags-sorter: order
    operations-sorter: order
    # 指定手动配置的模式(默认为该模式)
    strategy: manual
    routes:
      - name: 用户服务
        # 真实子服务访问url地址-提供OpenAPI的文档
        url: /bestoj-backend-user-service/api/v3/api-docs/default
        service-name: bestoj-backend-user-service
        # 路由前缀
        # 兼容OpenAPI3规范在聚合时丢失contextPath属性的异常情况，由开发者自己配置contextPath,Knife4j的前端Ui做兼容处理,与url属性独立不冲突，仅OpenAPI3规范聚合需要，OpenAPI2规范不需要设置此属性,默认为(apiPathPrefix)
        context-path: /api
        order: 2
      - name: 题目服务
        # 真实子服务访问url地址-提供OpenAPI的文档
        url: /bestoj-backend-question-service/api/v3/api-docs/default
        service-name: bestoj-backend-question-service
        # 路由前缀
        # 兼容OpenAPI3规范在聚合时丢失contextPath属性的异常情况，由开发者自己配置contextPath,Knife4j的前端Ui做兼容处理,与url属性独立不冲突，仅OpenAPI3规范聚合需要，OpenAPI2规范不需要设置此属性,默认为(apiPathPrefix)
        context-path: /api
        order: 3
      - name: 判题服务
        # 真实子服务访问url地址-提供OpenAPI的文档
        url: /bestoj-backend-judge-service/api/v3/api-docs/default
        service-name: bestoj-backend-judge-service
        # 路由前缀
        # 兼容OpenAPI3规范在聚合时丢失contextPath属性的异常情况，由开发者自己配置contextPath,Knife4j的前端Ui做兼容处理,与url属性独立不冲突，仅OpenAPI3规范聚合需要，OpenAPI2规范不需要设置此属性,默认为(apiPathPrefix)
        context-path: /api
        order: 4